package web

import "github.com/gin-gonic/gin"

var SHOWSEASONSRESP = gin.H{
	"data": gin.H{
		"1": gin.H{
			"airdate":      "2014-04-21",
			"file_size":    273208594,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E01E02 - Wake Up & Escape From the Citadel - HD TV.mkv",
			"name":         "Wake Up",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"2": gin.H{
			"airdate":      "2014-04-21",
			"file_size":    273208594,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E01E02 - Wake Up & Escape From the Citadel - HD TV.mkv",
			"name":         "Escape From the Citadel",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"3": gin.H{
			"airdate":      "2014-04-28",
			"file_size":    162132353,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E03 - James II - HD TV.mkv",
			"name":         "James II",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"4": gin.H{
			"airdate":      "2014-05-05",
			"file_size":    151180472,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E04 - The Tower - HD TV.mkv",
			"name":         "The Tower",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"5": gin.H{
			"airdate":      "2014-05-12",
			"file_size":    155137615,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E05 - Sad Face - HD TV.mkv",
			"name":         "Sad Face",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"6": gin.H{
			"airdate":      "2014-06-05",
			"file_size":    145338313,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E06 - Breezy - HD TV.mkv",
			"name":         "Breezy",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"7": gin.H{
			"airdate":      "2014-06-12",
			"file_size":    244514099,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E07 - Food Chain - HD TV.mkv",
			"name":         "Food Chain",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"8": gin.H{
			"airdate":      "2014-06-19",
			"file_size":    188755166,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E08 - Furniture & Meat - HD TV.mkv",
			"name":         "Furniture & Meat",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"9": gin.H{
			"airdate":      "2014-06-26",
			"file_size":    172387663,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E09 - The Prince Who Wanted Everything - HD TV.mkv",
			"name":         "The Prince Who Wanted Everything",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"10": gin.H{
			"airdate":      "2014-07-03",
			"file_size":    186948926,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E10 - Something Big - HD TV.mkv",
			"name":         "Something Big",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"11": gin.H{
			"airdate":      "2014-07-10",
			"file_size":    124084668,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E11 - Little Brother - HD TV.mkv",
			"name":         "Little Brother",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"12": gin.H{
			"airdate":      "2014-07-17",
			"file_size":    158117566,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E12 - Ocarina - HD TV.mkv",
			"name":         "Ocarina",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"13": gin.H{
			"airdate":      "2014-07-24",
			"file_size":    836560466,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E13E14 - Thanks for the Crabapples, Giuseppe & Princess Day - 1080p WEB-DL.mkv",
			"name":         "Thanks for the Crabapples, Giuseppe",
			"quality":      "1080p WEB-DL",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"14": gin.H{
			"airdate":      "2014-07-31",
			"file_size":    836560466,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E13E14 - Thanks for the Crabapples, Giuseppe & Princess Day - 1080p WEB-DL.mkv",
			"name":         "Princess Day",
			"quality":      "1080p WEB-DL",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"15": gin.H{
			"airdate":      "2014-08-07",
			"file_size":    171461972,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E15 - Nemesis - HD TV.mkv",
			"name":         "Nemesis",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"16": gin.H{
			"airdate":      "2014-08-14",
			"file_size":    171373209,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E16 - Joshua and Margaret Investigations - HD TV.mkv",
			"name":         "Joshua & Margaret Investigations",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"17": gin.H{
			"airdate":      "2014-10-28",
			"file_size":    170927325,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E17 - Ghost Fly - HD TV.mkv",
			"name":         "Ghost Fly",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"18": gin.H{
			"airdate":      "2014-11-24",
			"file_size":    163376987,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E18 - Everything's Jake - HD TV.mkv",
			"name":         "Everything's Jake",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"19": gin.H{
			"airdate":      "2014-11-25",
			"file_size":    166544734,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E19 - Is That You - HD TV.mkv",
			"name":         "Is That You?",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"20": gin.H{
			"airdate":      "2014-11-26",
			"file_size":    185958694,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E20 - Jake the Brick - HD TV.mkv",
			"name":         "Jake the Brick",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"21": gin.H{
			"airdate":      "2014-11-28",
			"file_size":    174695372,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E21 - Dentist - HD TV.mkv",
			"name":         "Dentist",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"22": gin.H{
			"airdate":      "2014-12-04",
			"file_size":    184468995,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E22 - The Cooler - HD TV.mkv",
			"name":         "The Cooler",
			"quality":      "HD TV",
			"release_name": "",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"23": gin.H{
			"airdate":      "2015-01-08",
			"file_size":    163892244,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E23 - The Pajama War.mkv",
			"name":         "The Pajama War",
			"quality":      "HD TV",
			"release_name": "Adventure.Time.S06E23.Pajama.Wars.720p.HDTV.x264-W4F",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"24": gin.H{
			"airdate":      "2015-01-15",
			"file_size":    190145167,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E24 - Evergreen.mkv",
			"name":         "Evergreen",
			"quality":      "HD TV",
			"release_name": "Adventure.Time.S06E24.Evergreen.720p.HDTV.x264-W4F",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"25": gin.H{
			"airdate":      "2015-01-22",
			"file_size":    169102152,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E25 - Astral Plane.mkv",
			"name":         "Astral Plane",
			"quality":      "HD TV",
			"release_name": "Adventure.Time.S06E25.Astral.Plane.720p.HDTV.x264-W4F",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"26": gin.H{
			"airdate":      "2015-01-29",
			"file_size":    183284277,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E26 - Gold Stars.mkv",
			"name":         "Gold Stars",
			"quality":      "HD TV",
			"release_name": "Adventure.Time.S06E26.Gold.Stars.720p.HDTV.x264-W4F",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"27": gin.H{
			"airdate":      "2015-02-05",
			"file_size":    360720356,
			"location":     "/mnt/nas/public/video/TV/Adventure Time/Season 06/Adventure Time - S06E27 - The Visitor.mkv",
			"name":         "The Visitor",
			"quality":      "1080p HD TV",
			"release_name": "Adventure.Time.S06E27.1080p.HDTV.x264-QCF",
			"status":       "Downloaded",
			"subtitles":    "",
		},
		"28": gin.H{
			"airdate":      "2015-02-12",
			"file_size":    0,
			"location":     "",
			"name":         "The Mountain",
			"quality":      "N/A",
			"release_name": "",
			"status":       "Unaired",
			"subtitles":    "",
		},
		"29": gin.H{
			"airdate":      "2015-02-19",
			"file_size":    0,
			"location":     "",
			"name":         "Dark Purple",
			"quality":      "N/A",
			"release_name": "",
			"status":       "Unaired",
			"subtitles":    "",
		},
		"30": gin.H{
			"airdate":      "2015-02-26",
			"file_size":    0,
			"location":     "",
			"name":         "The Diary",
			"quality":      "N/A",
			"release_name": "",
			"status":       "Unaired",
			"subtitles":    "",
		},
		"31": gin.H{
			"airdate":      "",
			"file_size":    0,
			"location":     "",
			"name":         "Jermaine",
			"quality":      "N/A",
			"release_name": "",
			"status":       "Skipped",
			"subtitles":    "",
		},
	},
	"message": "",
	"result":  "success",
}

var SHOWRESP = gin.H{
	"message": "",
	"result":  "success",
	"data": gin.H{
		"air_by_date":        0,
		"airs":               "Thursday 7:00 PM",
		"anime":              0,
		"archive_firstmatch": 0,
		"cache": gin.H{
			"banner": 1,
			"poster": 1,
		},
		"dvdorder":        0,
		"flatten_folders": 0,
		"genre": []string{
			"Adventure",
			"Animation",
			"Children",
			"Comedy",
		},
		"indexerid":       152831,
		"language":        "en",
		"location":        "/mnt/nas/public/video/TV/Adventure Time",
		"network":         "Cartoon Network",
		"next_ep_airdate": "2015-02-12",
		"paused":          0,
		"quality":         "HD",
		"quality_details": gin.H{
			"archive": []string{},
			"initial": []string{
				"hdtv",
				"fullhdtv",
				"hdwebdl",
				"fullhdwebdl",
				"hdbluray",
				"fullhdbluray",
			},
		},
		"rls_ignore_words":  []string{},
		"rls_require_words": []string{},
		"scene":             0,
		"season_list":       []int{6, 5, 4, 3, 2, 1, 0},
		"show_name":         "Adventure Time",
		"sports":            0,
		"status":            "Continuing",
	},
}
